### ISSUE TITLE
Setup the Register UI

### ISSUE THREAD

**Issue by kartikcode** [SPO-Career-Portal/SPC-Frontend#1]
Need to fix the authentication UI. Setup the Register page. It should contain the following fields:
- IITK Email address 
- Password field
- Confirm Password

<br/> Make sure to setup a  function to match the two entered passwords. Also, create a dummy API function to send in the data to backend. The data object should contain the email id and the password.

**Comment by navneet-28** [comment]
I'll be glad to work on this issue!

**Comment by uditpd3000** [comment]
I would like to work on this issue

**Comment by mridul911** [comment]
@navneet-28 @uditpd3000 Cool, work on it be in touch with members who are working on login, after submitting the form actions will be somewhat common for both of you.

**Comment by parinayc20** [comment]
@kartikcode @mridul911 may I also work on this issue? I have already contacted @navneet-28 , just want your confirmation.

**Comment by mridul911** [comment]
@parinayc20 2 persons in this task are more than sufficient. Please take Dashboard UI task you can ask someone if they want to work on that with you.
