### ISSUE TITLE
Integrate Profile Page with backend API

### ISSUE THREAD

**Issue by kartikcode** [SPO-Career-Portal/SPC-Frontend#16]
Checkout the backend repo and specifically this [PR](https://github.com/SPO-Career-Portal/SCP-Backend/pull/28). You will be required to make the necessary changes in the profile page too (add fields for master resume, resume 1 ,etc.) 
Connect it using preferably fetch API or react-axios.

**Comment by uditpd3000** [comment]
I want to work on this issue.
