### ISSUE TITLE
Setup the Login Page

### ISSUE THREAD

**Issue by kartikcode** [SPO-Career-Portal/SPC-Frontend#2]
Need to fix the Login Page UI. It should contain the following fields:

- IITK Email address
- Password field

Make sure to setup an email validator, which checks whether the typed email is valid or not. Also, create a dummy API function to send in the credentials to backend. The data object should contain the email id and the password. <br/>

**Comment by SahilSunda** [comment]
Ok great. I'm working on this issue.

**Comment by sanchit-sinha** [comment]
I'll also be working on this issue.

**Comment by Shubham63-hub** [comment]
SahilSunda and i are working in a team on this issue.

**Comment by mridul911** [comment]
I already added login actions that save responses using redux-react-session. I want you guys to make some good actions and reducers to handle this apart from what I added. If you have something else to save the session apart from redux-session use it as well as we don't want the user to log in again and again. As most part has been done, I think only one or max to max 2 of you can work on it.

**Comment by SahilSunda** [comment]
Yeah fine, shubham will work on profile one, me and sanchit can work on this
