### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by mridul911** [SPO-Career-Portal/SPC-Frontend#24]
Make a link for Reset password in Profile page or its dropdown. That will redirect us to the reset password page where user is asked for roll number. After that reset password mail will be sent. Design that reset password page as well. (GO to register PR if needed similar task is done there).
Some links for API you need to work upon.[#1](https://github.com/SPO-Career-Portal/SCP-Backend#reset-password-email) [#2](https://github.com/SPO-Career-Portal/SCP-Backend#reset-password)

**Comment by uditpd3000** [comment]
I want to work on this issue.
