### ISSUE TITLE
Setup the Profile Page

### ISSUE THREAD

**Issue by kartikcode** [SPO-Career-Portal/SPC-Frontend#3]
Make the Profile component generic. Accept the props `userId`. Upon loading the page, make a Fetch API call to fetch the relevant data about the user. This may include the following entities:
- Name
- Programme
- Department
- Roll No 
All these fields shall be non-editable.<br/>
The following fields are optional and can be edited by the user.
- Resume Link (drive link)
- Github profile link
- LinkedIn profile link<br/>
Create a dummy function which would be called upon clicking the `Save` button. This function shall update the user database.

**Comment by Shubham63-hub** [comment]
working in team with sahil sunda

**Comment by SahilSunda** [comment]
++
