### ISSUE TITLE
Setup Dashboard UI

### ISSUE THREAD

**Issue by kartikcode** [SPO-Career-Portal/SPC-Frontend#4]
Create the Dashboard UI where in we have a generic table displaying all the notifications regarding the offers. You might wanna used React Table 7. Here's the [link ](https://medium.com/@thewidlarzgroup/react-table-7-sorting-filtering-pagination-and-more-6bc28af104d6)for the same.

**Comment by parinayc20** [comment]
I want to work on this but could you please provide a more elaborate picture of what all features should I include in the dashboard because there are a lot of options.

**Comment by p-harsh** [comment]
Vedit and I also want to work on this.

**Comment by parinayc20** [comment]
> Vedit and I also want to work on this.

Ya I'd love to.

**Comment by mridul911** [comment]
After fetching data for the present companies available for user we need to render that using react-tables. Make dummy data that contains all values like name, company work, etc. as of now. Also, add a button that redirects us to a form(inside the app itself) that has some already filled data and some other fields that need to be filled by the user. This will be our landing page for most of the time so we need some good UI. You all can start working on it as a team or as you prefer.

**Comment by kartikcode** [comment]
So basically the object structure that you're gonna fetch will have the following details:
- Name of Organisation
- Job Profile
- Position (Internship/Job)
- Deadline
- Eligibility

On the expandable card action, display the following details:
- Job Details
- About the Company
- Apply button

On clicking the apply button, open up a modal form containing some sample fields. These would also be fetched from the backend as every company wants a different set of information. You can create a form using Argon's Form component, the relevant documentations can be found [here](https://demos.creative-tim.com/argon-dashboard-react/?_ga=2.216331152.721954090.1611939406-1910100466.1611850064#/documentation/forms).

Also, apply filters and sorting methods to various columns, where you think these would be required. Send in a PR with the following features implemented. Also, I think this is a fairly long task, maybe @parinayc20 , @h4rSHp and Vedit could work in collaboratively on this one. Try and distribute this into subtask. If you need some assistance, do let me know.

**Comment by kartikcode** [comment]
So basically the object structure that you're gonna fetch will have the following details:
- Name of Organisation
- Job Profile
- Position (Internship/Job)
- Deadline
- Eligibility

On the expandable card action, display the following details:
- Job Details
- About the Company
- Apply button

On clicking the apply button, open up a modal form containing some sample fields. These would also be fetched from the backend as every company wants a different set of information. You can create a form using Argon's Form component, the relevant documentations can be found [here](https://demos.creative-tim.com/argon-dashboard-react/?_ga=2.216331152.721954090.1611939406-1910100466.1611850064#/documentation/forms).

Also, apply filters and sorting methods to various columns, where you think these would be required. Send in a PR with the following features implemented. Also, I think this is a fairly long task, maybe @parinayc20 , @h4rSHp and Vedit could work in collaboratively on this one. Try and distribute this into subtask. If you need some assistance, do let me know.

**Comment by kartikcode** [comment]
Fixed with #6
